services:
  horien-purchase-agent:
    build: .
    container_name: horien-purchase-agent
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow 